name = "biofranjinha"
compatibility_date = "2024-01-01"

[env.production]
name = "biofranjinha"

[[env.production.routes]]
pattern = "biofranjinha.pages.dev/*"

[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

[build.environment_variables]
NODE_VERSION = "18"
